server:
  port: 8090
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Second-hand-transaction?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123789
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非null的字段
      update-strategy: not_empty

#图片上传
web:
  uploadpath: D:/images/  #图片上传的路径
  load-path: file:D://images/  #图片加载的路径

logging:
  pattern:
    console: '%d[yyyy-MM-dd] [%thread] %-5level %logger - %msg%n'

#jwt认证
jwt:
  #发布者
  issuer: lys
  #秘钥
  secret: com.lys
  #过期时间
  expiration: 30

alipay:
  appId:
  appPrivateKey:
  notifyUrl:







